#!/bin/bash
# Deployment script for test-email-to-sms
# Generated by: security-validation-test

set -e

echo "🚀 Deploying test-email-to-sms..."

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    echo "❌ Wrangler CLI not found. Installing..."
    npm install -g wrangler
fi

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Type check
echo "🔍 Type checking..."
npm run check

# Create KV namespaces if needed
echo "🗄️  Setting up KV namespaces..."
if ! wrangler kv:namespace list | grep -q "RATE_LIMIT_KV"; then
    echo "Creating RATE_LIMIT_KV namespace..."
    wrangler kv:namespace create "RATE_LIMIT_KV"
    echo "⚠️  Please update wrangler.toml with the namespace ID"
fi


# Check secrets
echo "🔐 Checking secrets..."
SECRETS_OK=true

if ! wrangler secret list | grep -q "TWILIO_ACCOUNT_SID"; then
    echo "⚠️  TWILIO_ACCOUNT_SID not set"
    SECRETS_OK=false
fi

if ! wrangler secret list | grep -q "TWILIO_AUTH_TOKEN"; then
    echo "⚠️  TWILIO_AUTH_TOKEN not set"
    SECRETS_OK=false
fi

if ! wrangler secret list | grep -q "TWILIO_PHONE_NUMBER"; then
    echo "⚠️  TWILIO_PHONE_NUMBER not set"
    SECRETS_OK=false
fi

if [ "$SECRETS_OK" = false ]; then
    echo ""
    echo "❌ Secrets are missing. Set them using:"
    echo "   wrangler secret put TWILIO_ACCOUNT_SID"
    echo "   wrangler secret put TWILIO_AUTH_TOKEN"
    echo "   wrangler secret put TWILIO_PHONE_NUMBER"
    echo ""
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Deploy
echo "🚢 Deploying worker..."
wrangler deploy

echo ""
echo "✅ Deployment complete!"
echo ""
echo "📧 Next steps:"
echo "1. Configure Email Routing in Cloudflare Dashboard"
echo "2. Add routing rule for: *@sms.test.example.com"
echo "3. Test by sending an email"
echo ""
echo "🔗 Worker URL: https://test-email-to-sms.test.example.com"
echo "🏥 Health check: https://test-email-to-sms.test.example.com/health"
echo ""